ProjetoMVC/Controllers/TipologiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoMVC.EDMX;

namespace ProjetoMVC.Controllers
{
    public class TipologiaController : Controller
    {
        private DB_SISCODHABEntities db = new DB_SISCODHABEntities();

        //
        // GET: /Tipologia/

        public ActionResult Index()
        {
            return View(db.TB_TIPOLOGIA.ToList());
        }

        //
        // GET: /Tipologia/Details/5

        public ActionResult Details(int id = 0)
        {
            TB_TIPOLOGIA tb_tipologia = db.TB_TIPOLOGIA.Find(id);
            if (tb_tipologia == null)
            {
                return HttpNotFound();
            }
            return View(tb_tipologia);
        }

        //
        // GET: /Tipologia/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tipologia/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TB_TIPOLOGIA tb_tipologia)
        {
            if (ModelState.IsValid)
            {
                db.TB_TIPOLOGIA.Add(tb_tipologia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb_tipologia);
        }

        //
        // GET: /Tipologia/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TB_TIPOLOGIA tb_tipologia = db.TB_TIPOLOGIA.Find(id);
            if (tb_tipologia == null)
            {
                return HttpNotFound();
            }
            return View(tb_tipologia);
        }

        //
        // POST: /Tipologia/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TB_TIPOLOGIA tb_tipologia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_tipologia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_tipologia);
        }

        //
        // GET: /Tipologia/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TB_TIPOLOGIA tb_tipologia = db.TB_TIPOLOGIA.Find(id);
            if (tb_tipologia == null)
            {
                return HttpNotFound();
            }
            return PartialView(tb_tipologia);
        }

        //
        // POST: /Tipologia/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_TIPOLOGIA tb_tipologia = db.TB_TIPOLOGIA.Find(id);
            db.TB_TIPOLOGIA.Remove(tb_tipologia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjetoMVC/Views/Tipologia/Create.cshtml
@model ProjetoMVC.EDMX.TB_TIPOLOGIA

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TB_TIPOLOGIA</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CO_TIPOLOGIA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CO_TIPOLOGIA)
            @Html.ValidationMessageFor(model => model.CO_TIPOLOGIA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NO_TIPOLOGIA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NO_TIPOLOGIA)
            @Html.ValidationMessageFor(model => model.NO_TIPOLOGIA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TIPO_HABITACAO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TIPO_HABITACAO)
            @Html.ValidationMessageFor(model => model.TIPO_HABITACAO)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AREA_PRIVATIVA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AREA_PRIVATIVA)
            @Html.ValidationMessageFor(model => model.AREA_PRIVATIVA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RENDA_FAM)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RENDA_FAM)
            @Html.ValidationMessageFor(model => model.RENDA_FAM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_INICIAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_INICIAL)
            @Html.ValidationMessageFor(model => model.VALOR_INICIAL)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_FINAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_FINAL)
            @Html.ValidationMessageFor(model => model.VALOR_FINAL)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoMVC/Views/Tipologia/Delete.cshtml
@model ProjetoMVC.EDMX.TB_TIPOLOGIA

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TB_TIPOLOGIA</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CO_TIPOLOGIA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CO_TIPOLOGIA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NO_TIPOLOGIA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NO_TIPOLOGIA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TIPO_HABITACAO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TIPO_HABITACAO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AREA_PRIVATIVA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AREA_PRIVATIVA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RENDA_FAM)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RENDA_FAM)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VALOR_INICIAL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VALOR_INICIAL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VALOR_FINAL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VALOR_FINAL)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ProjetoMVC/Views/Tipologia/Details.cshtml
@model ProjetoMVC.EDMX.TB_TIPOLOGIA

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>TB_TIPOLOGIA</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CO_TIPOLOGIA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CO_TIPOLOGIA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NO_TIPOLOGIA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NO_TIPOLOGIA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TIPO_HABITACAO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TIPO_HABITACAO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AREA_PRIVATIVA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AREA_PRIVATIVA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RENDA_FAM)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RENDA_FAM)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VALOR_INICIAL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VALOR_INICIAL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VALOR_FINAL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VALOR_FINAL)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjetoMVC/Views/Tipologia/Edit.cshtml
@model ProjetoMVC.EDMX.TB_TIPOLOGIA

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<h2>Editar Cliente</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TB_TIPOLOGIA</legend>

        @Html.HiddenFor(x => x.CO_TIPOLOGIA)

 
        <div class="editor-label">
            @Html.LabelFor(model => model.NO_TIPOLOGIA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NO_TIPOLOGIA)
            @Html.ValidationMessageFor(model => model.NO_TIPOLOGIA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TIPO_HABITACAO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TIPO_HABITACAO)
            @Html.ValidationMessageFor(model => model.TIPO_HABITACAO)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AREA_PRIVATIVA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AREA_PRIVATIVA)
            @Html.ValidationMessageFor(model => model.AREA_PRIVATIVA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RENDA_FAM)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RENDA_FAM)
            @Html.ValidationMessageFor(model => model.RENDA_FAM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_INICIAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_INICIAL)
            @Html.ValidationMessageFor(model => model.VALOR_INICIAL)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_FINAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_FINAL)
            @Html.ValidationMessageFor(model => model.VALOR_FINAL)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoMVC/Views/Tipologia/Index.cshtml
@model IEnumerable<TB_TIPOLOGIA>

@using GridMvc.Html
@using ProjetoMVC.EDMX

@{

    var teste = ViewBag.Model;

}
<script src="~/Scripts/jquery-2.1.0.min.js"></script>
<script src="~/Scripts/gridmvc.js"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/jquery-ui-1.10.4.custom.css" rel="stylesheet" />
<link href="~/Content/Gridmvc.css" rel="stylesheet" />



<script type="text/javascript">

    $(function () {

        $("#dialog").dialog({
            autoOpen: false,
            height: 355,
            width: 400
        });

        $(".modal-link").click(function () {
            $("#dialog").load(this.href, function () {
                $(this).dialog("open");
            });

            return false;
        });


        //$(".modal-link").click(function () {
        //    $("#dialog").load(this.href, function() {
        //        $(this).dialog("open");
        //    });
        //    return false;
        //});


        // pageGrids.Editar.onRowSelect(function (e) {
        //    $("teste").dialog("open");
        //    // alert(e.row.NO_TIPOLOGIA);
        //});


    });

</script>


<p>
    @Html.ActionLink("Create New", "Create")
</p>

@*@using (Html.BeginForm("UploadArquivo", "Tipologia", FormMethod.Post, new { enctype = "multipart/form-data" }))}
    {
        <div class="glyphicon-edit">
            <input type="file" id="Upload" name="Upload"/>

            <button id="btnSalvar" type="submit">Salvar</button>
        </div>

    }*@



@Html.Grid(Model).AutoGenerateColumns().Columns(x =>
        x.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs
        (
            o => @Html.ActionLink("Editar", "Edit", new { id = o.CO_TIPOLOGIA }, new { @class = "modal-link" }))

        ).Named("Editar").Filterable(true)




<div id="dialog" title="Basic dialog" style="display: none">

</div>



<button id="opener">Open Dialog</button>





<div class="row">
    <div class="span4">1</div>
    <div class="span8">2</div>

</div>







@helper CustomRenderingOfColumn(TB_TIPOLOGIA tipo)
{

}

ProjetoMVC/Views/Tipologia/_ModalCreateCliente.cshtml
@model ProjetoMVC.EDMX.TB_TIPOLOGIA

@{
    Layout = null
}
<h2>Cadastro de Clientes</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TB_TIPOLOGIA</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CO_TIPOLOGIA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CO_TIPOLOGIA)
            @Html.ValidationMessageFor(model => model.CO_TIPOLOGIA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NO_TIPOLOGIA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NO_TIPOLOGIA)
            @Html.ValidationMessageFor(model => model.NO_TIPOLOGIA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TIPO_HABITACAO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TIPO_HABITACAO)
            @Html.ValidationMessageFor(model => model.TIPO_HABITACAO)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AREA_PRIVATIVA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AREA_PRIVATIVA)
            @Html.ValidationMessageFor(model => model.AREA_PRIVATIVA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RENDA_FAM)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RENDA_FAM)
            @Html.ValidationMessageFor(model => model.RENDA_FAM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_INICIAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_INICIAL)
            @Html.ValidationMessageFor(model => model.VALOR_INICIAL)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VALOR_FINAL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VALOR_FINAL)
            @Html.ValidationMessageFor(model => model.VALOR_FINAL)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>